spring.application.name=springboot-backend-chat

# Base de datos Supabase (Session Pooler)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Evita problemas con Prepared Statements (opcional, pero recomendable)
spring.datasource.hikari.data-source-properties.prepareThreshold=0